- name: Install Latest Packages
  hosts: all
  become: yes 
  vars:
    packages:
      - curl
      - git
      - tree
  tasks:
    - name: install packages latest versions
      apt:
        name: "{{ item }}"
        state: latest
      loop: "{{ packages }}"
---
- name: Install Packages
  hosts: all
  become: yes
  vars:
    packages:
      - name: git
        state: latest  
      - name: python
        state: installed 
      - name: wget
        state: absent 
  tasks:
    - name: Install packages by state
      apt:
        name: "{{ item.name }}"
        state: "{{ item.state }}"
      loop: "{{ packages }}"


